[tool.poetry]
name = "bidssearchtool"
version = "1.0.0"
description = ""
authors = ["Mouna Cerra Cheraka <mouna.cerra-cheraka@chuv.ch>"]
license = "Apache 2.0"
readme = "README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = ">=3.9"
duckdb = "*"
streamlit = "*"
xlsxwriter = "*"
pyyaml = "*"
pyinstrument = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"