[project]
requires-python = ">=3.9"
name = "BIDS-Search-Tool"
version = "1.0.0"
description = ""
authors = [
  { name = "Mouna Cerra Cheraka", email = "mouna.cerra-cheraka@chuv.ch" },
]
readme = "README.md"

dependencies = [
    "duckdb",
    "streamlit",
    "xlsxwriter",
    "pyyaml",
    "pyinstrument"
]